version: "0.1"

services:
  front-end:
    restart: "unless-stopped"
    container_name: "mlcoach"
    #user: "${UID}:${GID}"
    build:
      context: "."
      dockerfile: "docker/Dockerfile"
    command: "python src/frontend.py"
    environment:
      DATA_DIR: /mnt/c/Users/postdoc/Documents/Database/born
    volumes:
      - ${PWD}:/app/work
      - /mnt/c/Users/postdoc/Documents/Database/born:/app/work/data
    ports:
      - "8050:8050"
    networks:
      - computing_api_default
#      - model-regist_default

networks:
  computing_api_default:
    external: true
#  model-regist_default:
#    external: true
