version: '3.7'

services:
  mlcoach:
    restart: "unless-stopped"
    container_name: "mlcoach"
    image: ghcr.io/mlexchange/mlex_mlcoach:main
    volumes:
      - $DATA_DIR:/app/work/data
    environment:
      DIR_MOUNT: "${DATA_DIR}"
      DATA_DIR: "/app/work/data"
      PROJECT_ID: "-1"
      SPLASH_URL: "http://splash:80/api/v0"
      MLEX_COMPUTE_URL: "http://job-service:8080/api/v0"
      MLEX_CONTENT_URL: "http://content-api:8000/api/v0"
      HOST_NICKNAME: "${HOST_NICKNAME}"
      TILED_KEY: "${TILED_KEY}"
      DEFAULT_TILED_URI: "${DEFAULT_TILED_URI}"
      DEFAULT_TILED_SUB_URI: "${DEFAULT_TILED_SUB_URI}"
      APP_HOST: "0.0.0.0"
      APP_PORT: "8050"
    ports:
      - 127.0.0.1:8062:8050
    depends_on:
      - splash
    networks:
      - computing_api_default

  splash_db:
    image: mongo:4.4
    container_name: splash_db
    working_dir: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
    volumes:
      - "${PWD}/database/:/data/db"
    networks:
      - computing_api_default

  splash:
    image: ghcr.io/als-computing/splash-ml:master
    container_name: splash
    environment:
      APP_MODULE: "tagging.api:app"
      LOGLEVEL: DEBUG
      MONGO_DB_URI: "mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@splash_db:27017"
      MAX_WORKERS: 1
    ports:
      - 127.0.0.1:8087:80
    depends_on:
      - splash_db
    networks:
      - computing_api_default

  classifier:
    image: ghcr.io/mlexchange/mlex_image_classification:main

networks:
  computing_api_default:
    external: true
