version: "3"

services:
  front-end:
    restart: "unless-stopped"
    container_name: "mlcoach"
    build:
      context: "."
      dockerfile: "docker/Dockerfile"
    environment:
      DATA_DIR: "${PWD}/data/"
    volumes:
      - ./data:/app/work/data
    ports:
      - "8062:8062"
    networks:
      - computing_api_default

networks:
  computing_api_default:
    external: true
