#FROM armswdev/tensorflow-arm-neoverse:latest
FROM sonoisa/deep-learning-coding:pytorch1.12.0_tensorflow2.9.1

COPY docker/requirements_arm64.txt requirements.txt
USER root
RUN apt-get update && sudo apt-get install -y --no-install-recommends \
         build-essential\
         libsm6 \
         libxext6 \
         libxrender-dev \
         ffmpeg  \
         graphviz \
         tree \
    python3-pip &&\
    pip3 install --upgrade pip

RUN pip3 install -r requirements.txt
RUN pip3 install pydantic
WORKDIR /app/work/
COPY src/ src/

CMD ["bash"]
