FROM python:3.9

COPY docker/requirements.txt requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential\
         libsm6 \
         libxext6 \
         libxrender-dev \
         ffmpeg  \
    python3-pip &&\
    pip install --upgrade pip  

RUN pip install -r requirements.txt

WORKDIR /app/work/
COPY src/ src/
COPY ../main.cfg main.cfg

CMD ["bash"]
#CMD ["export TF_ENABLE_ONEDNN_OPTS=1"]
