FROM armswdev/tensorflow-arm-neoverse:latest

COPY docker/requirements_arm64.txt requirements.txt

RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends \
         build-essential\
         libsm6 \
         libxext6 \
         libxrender-dev \
         ffmpeg  \
         graphviz \
         tree \
    python3-pip &&\
    pip install --upgrade pip

RUN sudo pip install -r requirements.txt

WORKDIR /app/work/
COPY src/ src/

CMD ["bash"]
